---
apiVersion: autoscaling.k8s.io/v1beta2
kind: VerticalPodAutoscaler
metadata:
  labels:
    app: node-termination-handler
    k8s-app: node-termination-handler
    name: node-termination-handler
  name: node-termination-handler
  namespace: kube-system
spec:
  targetRef:
    apiVersion: apps/v1
    kind: DaemonSet
    name: node-termination-handler
  updatePolicy:
    updateMode: Initial

