---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: nginx
  name: nginx
rules:
- apiGroups:
  - extensions
  resourceNames:
  - restrict-root
  resources:
  - podsecuritypolicies
  verbs:
  - use
