---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-confd
  namespace: default
data:
  default.conf: |
    server {
        listen 8080 default_server;
        access_log /dev/stdout main;
        error_log stderr;

        location /healthz {
          add_header Content-Type text/plain;
          return 200 'sooooo healthy';
        }

        location / {
          return 200 'So affordable, so available\n';
        }
    }
